src/Entity/Job.php
<?php

namespace App\Entity;

use App\Repository\JobRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JobRepository::class)]
class Job
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $country = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column]
    private ?bool $remote_allowed = null;

    #[ORM\Column]
    private ?int $salary_range_min = null;

    #[ORM\Column]
    private ?float $salary_range_max = null;

    #[ORM\ManyToOne(inversedBy: 'jobs')]
    private ?JobType $jobtype = null;

    /**
     * @var Collection<int, JobCategory>
     */
    #[ORM\ManyToMany(targetEntity: JobCategory::class, inversedBy: 'jobs')]
    private Collection $jobcategorys;

    #[ORM\ManyToOne(inversedBy: 'jobs')]
    private ?Company $company = null;

    /**
     * @var Collection<int, JobApplication>
     */
    #[ORM\OneToMany(targetEntity: JobApplication::class, mappedBy: 'Job')]
    private Collection $jobApplications;

    public function __construct()
    {
        $this->jobcategorys = new ArrayCollection();
        $this->jobApplications = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): static
    {
        $this->country = $country;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function isRemoteAllowed(): ?bool
    {
        return $this->remote_allowed;
    }

    public function setRemoteAllowed(bool $remote_allowed): static
    {
        $this->remote_allowed = $remote_allowed;

        return $this;
    }

    public function getSalaryRangeMin(): ?int
    {
        return $this->salary_range_min;
    }

    public function setSalaryRangeMin(int $salary_range_min): static
    {
        $this->salary_range_min = $salary_range_min;

        return $this;
    }

    public function getSalaryRangeMax(): ?float
    {
        return $this->salary_range_max;
    }

    public function setSalaryRangeMax(float $salary_range_max): static
    {
        $this->salary_range_max = $salary_range_max;

        return $this;
    }

    public function getJobtype(): ?JobType
    {
        return $this->jobtype;
    }

    public function setJobtype(?JobType $jobtype): static
    {
        $this->jobtype = $jobtype;

        return $this;
    }

    /**
     * @return Collection<int, JobCategory>
     */
    public function getJobcategorys(): Collection
    {
        return $this->jobcategorys;
    }

    public function addJobcategory(JobCategory $jobcategory): static
    {
        if (!$this->jobcategorys->contains($jobcategory)) {
            $this->jobcategorys->add($jobcategory);
        }

        return $this;
    }

    public function removeJobcategory(JobCategory $jobcategory): static
    {
        $this->jobcategorys->removeElement($jobcategory);

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }

    /**
     * @return Collection<int, JobApplication>
     */
    public function getJobApplications(): Collection
    {
        return $this->jobApplications;
    }

    public function addJobApplication(JobApplication $jobApplication): static
    {
        if (!$this->jobApplications->contains($jobApplication)) {
            $this->jobApplications->add($jobApplication);
            $jobApplication->setJob($this);
        }

        return $this;
    }

    public function removeJobApplication(JobApplication $jobApplication): static
    {
        if ($this->jobApplications->removeElement($jobApplication)) {
            // set the owning side to null (unless already changed)
            if ($jobApplication->getJob() === $this) {
                $jobApplication->setJob(null);
            }
        }

        return $this;
    }
}

src/Entity/JobType.php
<?php

namespace App\Entity;

use App\Repository\JobTypeRepository;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JobTypeRepository::class)]
class JobType
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    /**
     * @var Collection<int, Job>
     */
    #[ORM\OneToMany(targetEntity: Job::class, mappedBy: 'jobtype')]
    private Collection $jobs;

    public function __construct()
    {
        $this->jobs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Job>
     */
    public function getJobs(): Collection
    {
        return $this->jobs;
    }

    public function addJob(Job $job): static
    {
        if (!$this->jobs->contains($job)) {
            $this->jobs->add($job);
            $job->setJobtype($this);
        }

        return $this;
    }

    public function removeJob(Job $job): static
    {
        if ($this->jobs->removeElement($job)) {
            // set the owning side to null (unless already changed)
            if ($job->getJobtype() === $this) {
                $job->setJobtype(null);
            }
        }

        return $this;
    }
}

src/Form/JobForm.php
<?php

namespace App\Form;

use App\Entity\Company;
use App\Entity\Job;
use App\Entity\JobCategory;
use App\Entity\JobType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CountryType;


class JobForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', null, [
                'label' => 'Titre du poste',
            ])
            ->add('description', null, [
                'label' => 'Description',
            ])
            ->add('country', CountryType::class, [
                'label' => 'Pays',
                'placeholder' => 'Sélectionnez un pays',
            ])
            ->add('city', null, [
                'label' => 'Ville',
            ])
            ->add('remote_allowed', null, [
                'label' => 'Télétravail autorisé',
            ])
            ->add('salary_range_min', null, [
                'label' => 'Salaire minimum',
            ])
            ->add('salary_range_max', null, [
                'label' => 'Salaire maximum',
            ])
            ->add('jobtype', EntityType::class, [
                'class' => JobType::class,
                'choice_label' => 'name',
                'label' => 'Type de poste',
            ])
            ->add('jobcategorys', EntityType::class, [
                'class' => JobCategory::class,
                'choice_label' => 'name',
                'multiple' => true,
                'label' => 'Catégories',
            ])
            ->add('company', EntityType::class, [
                'class' => Company::class,
                'choice_label' => 'name',
                'label' => 'Entreprise',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Job::class,
        ]);
    }
}

src/Controller/JobController.php
<?php

namespace App\Controller;

use App\Entity\Job;
use App\Repository\JobRepository;
use App\Form\JobSearchType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\JobApplication;
use App\Form\PostulateTypeForm;
use App\Form\JobForm;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;

final class JobController extends AbstractController
{
    #[Route('/job/list', name: 'app_job_list')]
    public function index(JobRepository $jobRepository, EntityManagerInterface $em, Request $request): Response
    {
        $jobs = $jobRepository->findAll();

        $form = $this->createForm(JobSearchType::class, null, [
            'method' => 'GET',
        ]);

        return $this->render('job/list.html.twig', [
            'jobs' => $jobs,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/job/{id}', name: 'app_job_show')]
    public function show(
        Job $job,
        Security $security,
        EntityManagerInterface $em,
        Request $request
    ): Response {
        $user = $security->getUser();
        $hasApplied = false;
        $applicationForm = null;

        if ($user) {
            $existingApplication = $em->getRepository(JobApplication::class)
                ->findOneBy(['Job' => $job, 'utilisateur' => $user]);

            if ($existingApplication) {
                $hasApplied = true;
            } else {
                $application = new JobApplication();
                $application->setJob($job);
                $application->setUtilisateur($user);
                $application->setCreatedAt(new \DateTimeImmutable());

                $applicationForm = $this->createForm(PostulateTypeForm::class, $application, [
                    'action' => $this->generateUrl('app_job_postulate', ['id' => $job->getId()]),
                    'method' => 'POST',
                ]);
            }
        }

        return $this->render('job/show.html.twig', [
            'job' => $job,
            'hasApplied' => $hasApplied,
            'applicationForm' => $applicationForm ? $applicationForm->createView() : null,
            'isLoggedIn' => ($user !== null)
        ]);
    }

    #[Route('/ajouter-offre', name: 'app_job_add')]
    public function addJob(Request $request, EntityManagerInterface $em): Response
    {
        $job = new Job();
        $form = $this->createForm(JobForm::class, $job);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($job);
            $em->flush();

            $this->addFlash('success', 'Offre ajoutée avec succès !');
            return $this->redirectToRoute('app_home');
        }

        return $this->render('page/add_job.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/jobs', name: 'app_job_list')]
    public function list(Request $request, EntityManagerInterface $em): Response
    {
        $search = $request->query->get('search');
        $repository = $em->getRepository(Job::class);

        $form = $this->createForm(JobSearchType::class, null, [
            'method' => 'GET',
        ]);

        if ($search) {
            // Recherche avec critère
            $jobs = $repository->createQueryBuilder('j')
                ->where('j.title LIKE :search')
                ->orWhere('j.description LIKE :search')
                ->orWhere('j.city LIKE :search')
                ->orWhere('j.country LIKE :search')
                ->setParameter('search', '%' . $search . '%')
                ->orderBy('j.id', 'DESC')
                ->getQuery()
                ->getResult();
        } else {
            $jobs = $repository->findAll();
        }

        return $this->render('job/list.html.twig', [
            'jobs' => $jobs,
            'search' => $search,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/jobs/filtrer', name: 'app_job_filter')]
    public function filter(Request $request, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(JobSearchType::class);
        $form->handleRequest($request);
        
        $qb = $em->getRepository(Job::class)->createQueryBuilder('j')
            ->leftJoin('j.jobcategorys', 'c')
            ->leftJoin('j.company', 'comp');
        
        $category = $request->query->get('category');
        $salaryMin = $request->query->get('salary_min');
        $salaryMax = $request->query->get('salary_max');
        
        if ($category) {
            $qb->andWhere(':category MEMBER OF j.jobcategorys')
                ->setParameter('category', $category);
        }
        
        if ($salaryMin) {
            $qb->andWhere('j.salary_range_min >= :salaryMin')
                ->setParameter('salaryMin', $salaryMin);
        }
        
        if ($salaryMax) {
            $qb->andWhere('j.salary_range_max <= :salaryMax')
                ->setParameter('salaryMax', $salaryMax);
        }
        
        $jobs = $qb->getQuery()->getResult();
        
        return $this->render('job/list.html.twig', [
            'jobs' => $jobs,
            'form' => $form->createView(),
            'filters_applied' => ($category || $salaryMin || $salaryMax)
        ]);
    }
}

templates/job/list.html.twig
{% extends 'base.html.twig' %}
{% block title %}Liste des différents jobs
{% endblock %}
{% block body %}
	<section class="text-gray-400 bg-slate-700 body-font container px-5 py-14 mx-auto">
		<div
			class="container px-5 py-24 mx-auto">
			<div class="mb-8 bg-slate-800 p-6 rounded-lg">
				<h3 class="text-xl font-medium text-white mb-4">Filtrer les offres</h3>
				{{ form_start(form, {'method': 'GET', 'action': path('app_job_filter')}) }}
				<div class="flex flex-wrap gap-4 items-end">
					<div class="w-full md:w-1/3">
						{{ form_label(form.category, null, {'label_attr': {'class': 'text-gray-200'}}) }}
						{{ form_widget(form.category, {'attr': {'class': 'form-select w-full text-white bg-slate-800 border border-slate-600 rounded py-2 px-3'}}) }}
					</div>
					<div class="w-full md:w-1/4">
						{{ form_label(form.salary_min, null, {'label_attr': {'class': 'text-gray-200'}}) }}
						{{ form_widget(form.salary_min, {'attr': {'class': 'form-control w-full bg-slate-800 border border-slate-600 rounded py-2 px-3 text-gray-100'}}) }}
					</div>
					<div class="w-full md:w-1/4">
						{{ form_label(form.salary_max, null, {'label_attr': {'class': 'text-gray-200'}}) }}
						{{ form_widget(form.salary_max, {'attr': {'class': 'form-control w-full bg-slate-800 border border-slate-600 rounded py-2 px-3 text-gray-100'}}) }}
					</div>
					<div>
						<button class="text-white bg-secondary border-0 py-2 px-6 rounded" type="submit">Filtrer</button>
					</div>
				</div>
				{{ form_end(form) }}
			</div>

			{% if filters_applied is defined and filters_applied %}
				<div class="flex flex-col text-center w-full mb-12">
					<h2 class="text-2xl font-medium title-font mb-4 text-white">Résultats de filtrage</h2>
					<p class="lg:w-2/3 mx-auto text-base">
						{{ jobs|length }}
						offre(s) trouvée(s)
					</p>
				</div>
			{% endif %}

			{% if search is defined and search %}
				<div class="flex flex-col text-center w-full mb-12">
					<h2 class="text-2xl font-medium title-font mb-4 text-white">Résultats de recherche pour: "{{ search }}"</h2>
					<p class="lg:w-2/3 mx-auto text-base">
						{{ jobs|length }}
						résultat(s) trouvé(s)
					</p>
				</div>
			{% endif %}

			<div class="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4">
				{% if jobs|length > 0 %}
					{% for job in jobs %}
						{% include 'jobs/_jobs_item.html.twig' with {'job': job} %}
					{% endfor %}
				{% else %}
					<div class="w-full text-center py-10">
						<p class="text-xl text-white">Aucun job correspondant à votre recherche.</p>
					</div>
				{% endif %}
			</div>
		</div>
	</section>
{% endblock %}

templates/job/postulate.html.twig
{% extends 'base.html.twig' %}

{% block title %}Postuler à {{ job.title }}{% endblock %}

{% block body %}
<section class="text-gray-400 bg-slate-700 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-12">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-4 text-white">Postuler à {{ job.title }}</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
                Entreprise: {{ job.company.name }}
            </p>
        </div>
        
        <div class="lg:w-1/2 md:w-2/3 mx-auto">
            {{ form_start(form, {'attr': {'class': 'flex flex-wrap -m-2'}}) }}
                <div class="p-2 w-full">
                    <div class="relative">
                        {{ form_label(form.coverLetter, null, {'label_attr': {'class': 'leading-7 text-sm text-gray-400'}}) }}
                        {{ form_widget(form.coverLetter) }}
                        {{ form_errors(form.coverLetter) }}
                    </div>
                </div>
                <div class="p-2 w-full">
                    <button class="flex mx-auto text-white bg-secondary border-0 py-2 px-8 focus:outline-none hover:bg-teal-700 rounded text-lg">Envoyer ma candidature</button>
                </div>
            {{ form_end(form) }}
        </div>
    </div>
</section>
{% endblock %}

templates/job/show.html.twig
{% extends "base.html.twig" %}
{% block title %}
	{{ job.title }} - {{ job.company.name }}
{% endblock %}
{% block body %}
	<section class="text-gray-400 bg-slate-700 body-font">
		<div class="container px-5 py-24 mx-auto flex flex-wrap">
			<div class="flex flex-wrap -mx-4 lg:w-1/2 sm:w-2/3 content-between">
				<div class="w-full sm:p-4 px-4 mb-6">
					<div class="flex items-center mb-4">
						<h1 class="title-font font-medium text-3xl text-white">{{ job.title }}</h1>
						<span class="bg-secondary text-white text-sm px-3 py-1 ml-4 rounded-full">{{ job.jobtype.name }}</span>
					</div>

					<div class="flex items-center mb-6">
						<span class="inline-flex items-center text-gray-300 mr-6">
							<svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5 mr-2" viewbox="0 0 24 24">
								<path d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4"></path>
							</svg>
							{{ job.company.name }}
						</span>
					</div>

					<div class="leading-relaxed text-lg">
						{{ job.description|raw }}
					</div>
				</div>

				<div class="p-4 sm:w-1/2 lg:w-1/4 w-1/2">
					<h2 class="title-font font-medium text-xl text-white pb-2">Pays :</h2>
					<p class="leading-relaxed">{{ job.country }}</p>
				</div>
				<div class="p-4 sm:w-1/2 lg:w-1/4 w-1/2">
					<h2 class="title-font font-medium text-xl text-white pb-2">Ville :</h2>
					<p class="leading-relaxed">{{ job.city }}</p>
				</div>
				<div class="p-4 sm:w-1/2 lg:w-1/4 w-1/2">
					<h2 class="title-font font-medium text-xl text-white pb-2">Télétravail :</h2>
					<p class="leading-relaxed">{{ job.remoteAllowed ? 'Autorisé' : 'Non autorisé' }}</p>
				</div>
				<div class="p-4">
					<h2 class="title-font font-medium text-xl text-white pb-2">Salaire :</h2>
					<p class="leading-relaxed">{{ job.salaryRangeMin ? 'De ' ~ job.salaryRangeMin ~ ' à ' ~ job.salaryRangeMax ~ '€' : ''}}</p>
				</div>
			</div>

			{# Colonne de droite pour le formulaire de candidature #}
			<div class="lg:w-1/2 sm:w-1/3 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
				<div class="bg-slate-800 p-6 rounded-lg">
					<h2 class="title-font font-medium text-xl text-white pb-4">Postuler à cette offre</h2>

					{% if not isLoggedIn %}
						<div class="bg-slate-700 p-4 rounded">
							<p class="text-white mb-3">Vous devez être connecté pour postuler à cette offre.</p>
							<a href="{{ path('app_login') }}" class="inline-flex text-white bg-secondary border-0 py-2 px-6 focus:outline-none hover:bg-teal-700 rounded">Se connecter</a>
						</div>
					{% elseif hasApplied %}
						<div class="bg-teal-900 text-white p-4 rounded">
							<p>Vous avez déjà postulé à cette offre.</p>
						</div>
					{% else %}
						{{ form_start(applicationForm, {'attr': {'class': 'flex flex-wrap -m-2'}}) }}
						<div class="p-2 w-full">
							<div class="relative">
								{{ form_label(applicationForm.coverLetter, null, {'label_attr': {'class': 'leading-7 text-sm text-gray-400'}}) }}
								{{ form_widget(applicationForm.coverLetter) }}
								{{ form_errors(applicationForm.coverLetter) }}
							</div>
						</div>
						<div class="p-2 w-full">
							<button type="submit" class="flex mx-auto text-white bg-secondary border-0 py-2 px-8 focus:outline-none hover:bg-teal-700 rounded text-lg">Envoyer ma candidature</button>
						</div>
						{{ form_end(applicationForm) }}
					{% endif %}
				</div>
			</div>
		</div>
	</section>
{% endblock %}